version: '3'
services:
 db:
  image: microsoft/mssql-server-windows-express
  ports:
   - "1433:1433"
  volumes:
   - data-volume:c:\data
 cache:
  image: learningwsc/redis-server
  ports:
   - "6379:6379"
 web:
  build: .
  image: webserver:latest
  container_name: webcontainer
  ports:
   - "80:80"
  depends_on:
   - db
   - cache
  environment:
   - db_connection = db
   - cache_connection = cache
networks:
 default:
  driver: nat
  ipam:
   driver: default
   config:
    - subnet: 172.20.81.0/24
volumes:
 data-volume: